### ISSUE TITLE
cursive not found

### ISSUE THREAD

**Issue by ggbioing** [LaRiffle/collateral-learning#1]
https://github.com/LaRiffle/collateral-learning/blob/a8e40193e234e331fe49a5b0e1207b34464efa16/tutorials/Part%2001%20-%20Building%20a%202%20target%20features%20dataset.ipynb#L77
From which source/url we can download the 'cursive' font?
The 'Georgia' font was easy to find and install. I'm having hard time in finding the 'cursive' one.
Thanks!

**Comment by MikeLasz** [comment]
Hi @ggbioing , 
I stumbled across the same problem as well. I think you the authors have used the Felipa font: https://fonts.google.com/specimen/Felipa?query=Felipa#standard-styles 
Although I am not 100% sure whether the authors used the same font, it looks very very similar to the one in their tutorials. 

After deleting the matplotlib font cache (, which forces matplotlib to rewrite this file) and rerunning the code, it should work.

**Comment by LaRiffle** [comment]
Thanks a lot for the hint @MikeLasz, actually those fonts were by default on my Mac, but I guess any two fonts can be an interesting subject study :)
